workflows:

  test:
    name: Test
    instance_type: mac_mini
    max_build_duration: 10          # build duration in minutes (min 1, max 120)
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:                       # List the events that trigger the workflow
        - pull_request
        - push
        - tag
      cancel_previous_builds: true  # Automatically cancel outdated webhook builds
      branch_patterns:              # Include or exclude watched branches
        - pattern: '*'
          include: true
          source: true
        - pattern: excluded-target
          include: false
          source: false
        - pattern: included-source
          include: true
          source: true
    when:
      changeset:
        includes:
          - '.'
        excludes:
          - '**/*.md'
    scripts:
      - &test                       # Defined section; can be reused elsewhere using *test
        name: test
        script: |
          echo "Testing the app"
          flutter test
