name: recipe
description: A multi-platform Flutter app to showcase Typesense search.

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lints: ^1.0.1
  dartz: ^0.10.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+3
  typesense: ^0.2.0
  infinite_scroll_pagination: ^3.1.0
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.1"
  mockito: ^5.0.16
  build_runner: ^2.1.4
  bloc_test: ^9.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/recipe.svg
    - assets/images/recipe-transparent.svg

  fonts:
    - family: Averia Serif Libre
      fonts:
        - asset: assets/fonts/AveriaSerifLibre-Regular.ttf
